#!/bin/bash
#
#$ -cwd
#$ -q all.q
#$ -S /bin/bash
#$ -m e 

cd /storage/projects//MEFmono

#calculate aggregate profiles
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr1_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr1.bed --chromosome=chr1 --save_aligned --gzip --window=1 --force --aligned=chr1.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr2_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr2.bed --chromosome=chr2 --save_aligned --gzip --window=1 --force --aligned=chr2.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr3_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr3.bed --chromosome=chr3 --save_aligned --gzip --window=1 --force --aligned=chr3.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr4_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr4.bed --chromosome=chr4 --save_aligned --gzip --window=1 --force --aligned=chr4.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr5_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr5.bed --chromosome=chr5 --save_aligned --gzip --window=1 --force --aligned=chr5.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr6_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr6.bed --chromosome=chr6 --save_aligned --gzip --window=1 --force --aligned=chr6.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr7_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr7.bed --chromosome=chr7 --save_aligned --gzip --window=1 --force --aligned=chr7.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr8_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr8.bed --chromosome=chr8 --save_aligned --gzip --window=1 --force --aligned=chr8.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr9_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr9.bed --chromosome=chr9 --save_aligned --gzip --window=1 --force --aligned=chr9.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr10_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr10.bed --chromosome=chr10 --save_aligned --gzip --window=1 --force --aligned=chr10.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr11_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr11.bed --chromosome=chr11 --save_aligned --gzip --window=1 --force --aligned=chr11.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr12_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr12.bed --chromosome=chr12 --save_aligned --gzip --window=1 --force --aligned=chr12.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr13_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr13.bed --chromosome=chr13 --save_aligned --gzip --window=1 --force --aligned=chr13.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr14_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr14.bed --chromosome=chr14 --save_aligned --gzip --window=1 --force --aligned=chr14.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr15_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr15.bed --chromosome=chr15 --save_aligned --gzip --window=1 --force --aligned=chr15.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr16_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr16.bed --chromosome=chr16 --save_aligned --gzip --window=1 --force --aligned=chr16.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr17_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr17.bed --chromosome=chr17 --save_aligned --gzip --window=1 --force --aligned=chr17.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr18_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr18.bed --chromosome=chr18 --save_aligned --gzip --window=1 --force --aligned=chr18.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chr19_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chr19.bed --chromosome=chr19 --save_aligned --gzip --window=1 --force --aligned=chr19.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chrX_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chrX.bed --chromosome=chrX --save_aligned --gzip --window=1 --force --aligned=chrX.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000
perl /storage/projects/nuctools.2.0/aggregate_profile.pl --regions=/storage/projects/BS831_students/Coordinates/CTCF_MEF_intersect_ESC_mm9_added_IDs.bed --average_aligned=chrY_MEF-DKFZ1_AT_CTCF_MEF_intersect_ESC_mm9.txt  --chromosome_col=0 --region_start_column=1 --region_end_column=2 --strand_column=5  --GeneId_column=3 --ignore_strand --input=/storage/projects//MEFmono/1_occup_chrY.bed --chromosome=chrY --save_aligned --gzip --window=1 --force --aligned=chrY.aligned.tab_ESC-nucs_at_CTCF_MEF_intersect_ESC_mm9_added_IDs.bed.gz --useCenter --upstream_delta=2000 --downstream_delta=2000